# Generated by Django 3.1.1 on 2020-10-30 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup_finder_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_name',
            field=models.CharField(default='no name given', max_length=200),
            preserve_default=False,
        ),
    ]
