# Generated by Django 3.1.1 on 2020-11-06 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup_finder_app', '0002_event_event_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='lat',
            field=models.FloatField(default=38.036411),
        ),
        migrations.AddField(
            model_name='event',
            name='lng',
            field=models.FloatField(default=-78.502455),
        ),
    ]
