# Generated by Django 3.1.1 on 2020-11-06 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialaccount', '0003_extra_data_default_dict'),
        ('meetup_finder_app', '0003_auto_20201106_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialaccount.socialaccount'),
        ),
    ]
