# Generated by Django 3.1.1 on 2020-11-06 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetup_finder_app', '0003_auto_20201106_2002'),
        ('meetup_finder_app', '0004_delete_customer'),
    ]

    operations = [
    ]
