# Generated by Django 3.1.1 on 2020-11-11 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialaccount', '0003_extra_data_default_dict'),
        ('meetup_finder_app', '0005_merge_20201106_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='interested_users',
            field=models.ManyToManyField(to='socialaccount.SocialAccount'),
        ),
    ]
