# Generated by Django 3.1.1 on 2020-11-22 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetup_finder_app', '0004_auto_20201106_1356'),
        ('meetup_finder_app', '0009_auto_20201117_2347'),
    ]

    operations = [
    ]
