# Generated by Django 3.1.1 on 2020-11-23 01:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meetup_finder_app', '0010_merge_20201122_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='requested_friends',
            field=models.ManyToManyField(to='meetup_finder_app.AppUser'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
